### ISSUE TITLE
ImportError: cannot import name 'TapasForQuestionAnswering' from 'transformers' (unknown location)

### ISSUE THREAD

**Issue by wentinghome** [NielsRogge/tapas_utils#4]
Hi,

I tried to execute from transformers import TapasForQuestionAnswering, the err shows up "ImportError: cannot import name 'TapasForQuestionAnswering' from 'transformers' (unknown location)".

My env is transformer 4.6.0 with pytorch 1.8.0, and I also install pytorch-scatter as required.

Could you suggest how to import TapasForQuestionAnswering? Thank you so much!

**Comment by NielsRogge** [comment]
Hi, can you share a Colab to reproduce this?

**Comment by wentinghome** [comment]
> Hi, can you share a Colab to reproduce this?

Hi, thanks for your reply. I fixed it, it worked on python 3.6 rather than 3.7 in my conda env.
